#!/usr/bin/env python3
"""Deterministic MCP tool-module generator for the ``docs_preview`` service.

Reads committed Google API discovery documents plus a hand-written Developer
Preview overlay and emits Python tool modules into ``gdocs_preview/generated/``.

Inputs (all committed to the repo):
  - codegen/discovery/docs-v1.json          public Docs v1 discovery
  - codegen/discovery/drive-v3.json         public Drive v3 discovery
  - codegen/overlay/docs_preview_overlay.json
        discovery-format overlay carrying the July 2026 Docs API Developer
        Preview surface (absent from public discovery). Post-enrollment this
        file is replaced by real discovery output with no generator changes.
  - codegen/overlay/generator_config.json   generator-owned metadata
        (SUGGEST-write-mode compatibility) that survives overlay replacement.

Outputs (committed; regenerate with ``python codegen/generate.py``):
  - gdocs_preview/generated/__init__.py
  - gdocs_preview/generated/docs_methods.py       documents.get/create/batchUpdate
  - gdocs_preview/generated/docs_batch_update.py  one tool per GA Request member
  - gdocs_preview/generated/docs_preview.py       one tool per preview Request member
  - gdocs_preview/generated/drive_comments.py     Drive v3 comments.* / replies.*
  - gdocs_preview/generated/manifest.json         machine-readable tool inventory

The generator is deterministic: identical inputs produce byte-identical
outputs (all iteration is sorted, no timestamps are embedded).
"""

from __future__ import annotations

import argparse
import copy
import json
import re
import textwrap
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DISCOVERY_DIR = REPO_ROOT / "codegen" / "discovery"
OVERLAY_PATH = REPO_ROOT / "codegen" / "overlay" / "docs_preview_overlay.json"
CONFIG_PATH = REPO_ROOT / "codegen" / "overlay" / "generator_config.json"
DEFAULT_OUT_DIR = REPO_ROOT / "gdocs_preview" / "generated"

WIDTH = 88

GENERATED_HEADER = '''"""AUTO-GENERATED by codegen/generate.py. DO NOT EDIT BY HAND.

Regenerate with: python codegen/generate.py
Sources: committed discovery documents under codegen/discovery/ plus the
Developer Preview overlay codegen/overlay/docs_preview_overlay.json.
"""
'''

# Fields whose descriptions are always spelled out in "Returns:" documentation
# (id/author documentation is a hard requirement for this service).
IMPORTANT_RESPONSE_FIELDS = {
    "anchor",
    "author",
    "commentId",
    "commentUpdateState",
    "id",
    "postId",
    "quotedFileContent",
    "replies",
    "resolved",
    "suggestionId",
    "suggestionResponses",
}


def snake(name: str) -> str:
    """Convert camelCase/PascalCase to snake_case."""
    out = re.sub(r"(?<=[a-z0-9])(?=[A-Z])", "_", name)
    out = re.sub(r"(?<=[A-Z])(?=[A-Z][a-z])", "_", out)
    return out.lower()


def pascal(member: str) -> str:
    return member[0].upper() + member[1:]


def normalize_text(text: str) -> str:
    """Collapse whitespace and neutralise characters that would break docstrings."""
    text = " ".join((text or "").split())
    text = text.replace("\\", "\\\\")
    text = text.replace('"""', "'''")
    return text


def first_sentence(text: str) -> str:
    text = normalize_text(text)
    idx = text.find(". ")
    if idx != -1:
        text = text[: idx + 1]
    return text


def load_json(path: Path) -> dict:
    with open(path, encoding="utf-8") as fh:
        return json.load(fh)


def merge_overlay(base: dict, overlay: dict) -> tuple[dict, set[str], set[str]]:
    """Merge an overlay discovery fragment into a base discovery document.

    Returns (merged, preview_request_members, preview_schema_names).
    Schemas present only in the overlay are added; schemas present in both have
    their properties merged (overlay wins per property). Resource methods merge
    the same way. This works identically whether the overlay is the hand-written
    fragment or a full discovery document fetched with preview visibility.
    """
    merged = copy.deepcopy(base)
    base_request_members = set(
        base.get("schemas", {}).get("Request", {}).get("properties", {})
    )
    preview_schemas = set()

    for schema_name, schema in overlay.get("schemas", {}).items():
        target = merged.setdefault("schemas", {})
        if schema_name not in target:
            target[schema_name] = copy.deepcopy(schema)
            preview_schemas.add(schema_name)
            continue
        existing = target[schema_name]
        for prop_name, prop in schema.get("properties", {}).items():
            existing.setdefault("properties", {})[prop_name] = copy.deepcopy(prop)

    for res_name, resource in overlay.get("resources", {}).items():
        target_res = merged.setdefault("resources", {}).setdefault(res_name, {})
        for m_name, method in resource.get("methods", {}).items():
            target_res.setdefault("methods", {})[m_name] = copy.deepcopy(method)

    preview_members = (
        set(merged.get("schemas", {}).get("Request", {}).get("properties", {}))
        - base_request_members
    )
    return merged, preview_members, preview_schemas


# ---------------------------------------------------------------------------
# Type mapping


SCALAR_TYPES = {
    "string": "str",
    "integer": "int",
    "number": "float",
    "boolean": "bool",
}


def prop_annotation(prop: dict) -> tuple[str, set[str]]:
    """Return (python annotation for Optional param, needed special imports)."""
    if "$ref" in prop:
        return "Optional[JsonDict]", {"JsonDict"}
    ptype = prop.get("type")
    if ptype == "object":
        return "Optional[JsonDict]", {"JsonDict"}
    if ptype == "array":
        items = prop.get("items", {})
        if "$ref" in items or items.get("type") == "object":
            return "Optional[DictList]", {"DictList"}
        if items.get("type") == "string":
            return "Optional[StringList]", {"StringList"}
        return "Optional[ObjectList]", {"ObjectList"}
    return f"Optional[{SCALAR_TYPES.get(ptype, 'str')}]", set()


def prop_type_label(prop: dict) -> str:
    """Human-readable type label for docstrings."""
    if "$ref" in prop:
        return prop["$ref"]
    ptype = prop.get("type", "any")
    if ptype == "array":
        items = prop.get("items", {})
        inner = items.get("$ref") or items.get("type", "any")
        return f"array<{inner}>"
    return ptype


def schema_fields_summary(schema: dict, spell_out: bool = False) -> list[str]:
    """One entry per top-level property: 'name (type)' with optional description."""
    entries = []
    for name in sorted(schema.get("properties", {})):
        prop = schema["properties"][name]
        label = f"{name} ({prop_type_label(prop)})"
        if spell_out or name in IMPORTANT_RESPONSE_FIELDS:
            desc = first_sentence(prop.get("description", ""))
            if desc:
                label += f": {desc}"
        entries.append(label)
    return entries


# ---------------------------------------------------------------------------
# Docstring assembly


def wrap_block(text: str, indent: int, hanging: int | None = None) -> list[str]:
    initial = " " * indent
    subsequent = " " * (hanging if hanging is not None else indent)
    return textwrap.wrap(
        text,
        width=WIDTH,
        initial_indent=initial,
        subsequent_indent=subsequent,
        break_long_words=False,
        break_on_hyphens=False,
    ) or [initial.rstrip()]


class DocstringBuilder:
    def __init__(self, summary: str):
        self.lines: list[str] = [f'    """{summary}']

    def blank(self):
        if self.lines[-1] != "":
            self.lines.append("")

    def para(self, text: str, indent: int = 4):
        self.blank()
        self.lines.extend(wrap_block(normalize_text(text), indent))

    def section(self, title: str):
        self.blank()
        self.lines.append(f"    {title}")

    def item(self, text: str):
        self.lines.extend(wrap_block(text, 8, 12))

    def render(self) -> list[str]:
        out = list(self.lines)
        out.append('    """')
        return out


# ---------------------------------------------------------------------------
# Tool emission


class ToolSpec:
    """Fully-resolved description of one generated tool."""

    def __init__(self, name: str):
        self.name = name
        self.title = ""
        self.kind = ""  # "method" | "batch_member"
        self.module = ""
        self.preview = False
        self.service_type = ""  # "docs" | "drive"
        self.scope_group = ""
        self.read_only = False
        self.destructive = False
        self.params: list[dict] = []  # signature order
        self.doc_lines: list[str] = []
        self.body_lines: list[str] = []
        self.imports: set[str] = set()
        self.source = ""  # e.g. "docs.documents.get" or member name
        self.write_mode = False

    def render(self) -> list[str]:
        lines = [
            "@server.tool(",
            f'    title="{self.title}",',
            "    annotations=ToolAnnotations(",
            f"        readOnlyHint={self.read_only},",
            f"        destructiveHint={self.destructive},",
            f"        idempotentHint={self.read_only},",
            "        openWorldHint=True,",
            "    ),",
            ")",
            f'@handle_http_errors("{self.name}"'
            + (", is_read_only=True" if self.read_only else "")
            + f', service_type="{self.service_type}")',
            f'@require_google_service("{self.service_type}", "{self.scope_group}")',
            f"async def {self.name}(",
            "    service: Any,",
            "    user_google_email: str,",
        ]
        for param in self.params:
            default = param.get("default_src")
            if default is None:
                lines.append(f"    {param['py_name']}: {param['annotation']},")
            else:
                lines.append(
                    f"    {param['py_name']}: {param['annotation']} = {default},"
                )
        lines.append(") -> str:")
        lines.extend(self.doc_lines)
        lines.extend(self.body_lines)
        return lines


def make_param(
    py_name: str,
    annotation: str,
    doc: str,
    wire_name: str,
    required: bool = False,
    default_src: str | None = "None",
) -> dict:
    return {
        "py_name": py_name,
        "annotation": annotation,
        "doc": doc,
        "wire_name": wire_name,
        "required": required,
        "default_src": None if required else default_src,
    }


def doc_params_section(builder: DocstringBuilder, params: list[dict]):
    builder.section("Args:")
    builder.item("user_google_email (str): The user's Google email address. Required.")
    for param in params:
        annotation = param["annotation"]
        base_type = (
            annotation[len("Optional[") : -1]
            if annotation.startswith("Optional[") and annotation.endswith("]")
            else annotation
        )
        if base_type.startswith("Literal["):
            base_type = "str"
        display = {
            "JsonDict": "dict",
            "DictList": "list[dict]",
            "StringList": "list[str]",
            "ObjectList": "list",
        }.get(base_type, base_type)
        builder.item(f"{param['py_name']} ({display}): {param['doc']}")


def enum_doc(prop: dict) -> str:
    if "enum" in prop:
        return " Values: " + " | ".join(prop["enum"]) + "."
    return ""


def ref_schema_doc(prop: dict, schemas: dict) -> str:
    """Inline one level of a referenced object schema for a dict parameter."""
    ref = prop.get("$ref") or prop.get("items", {}).get("$ref")
    if not ref or ref not in schemas:
        return ""
    fields = ", ".join(schema_fields_summary(schemas[ref]))
    return f" Object schema {ref}: {{{fields}}}."


def build_method_tool(
    api_name: str,
    resource_name: str,
    resource_attr: str,
    method_name: str,
    method: dict,
    schemas: dict,
    preview: bool,
    service_type: str,
    read_group: str,
    write_group: str,
    add_fields_param: bool,
) -> ToolSpec:
    http = method.get("httpMethod", "GET")
    read_only = http == "GET"
    tool_name = f"{api_name}_api_{resource_name}_{snake(method_name)}"
    spec = ToolSpec(tool_name)
    spec.kind = "method"
    spec.source = method.get("id", f"{resource_name}.{method_name}")
    spec.preview = preview
    spec.service_type = service_type
    spec.scope_group = read_group if read_only else write_group
    spec.read_only = read_only
    spec.destructive = http == "DELETE"
    api_title = "Docs" if service_type == "docs" else "Drive"
    spec.title = f"{api_title} API: {resource_name}.{method_name}"

    parameters = method.get("parameters", {})
    order = list(method.get("parameterOrder", []))
    required_names = [p for p in order if p in parameters]
    for extra in sorted(parameters):
        if parameters[extra].get("required") and extra not in required_names:
            required_names.append(extra)
    optional_names = sorted(p for p in parameters if p not in required_names)

    params: list[dict] = []
    for pname in required_names:
        prop = parameters[pname]
        annotation = SCALAR_TYPES.get(prop.get("type"), "str")
        doc = first_sentence(prop.get("description", "")) + enum_doc(prop)
        params.append(make_param(snake(pname), annotation, doc, pname, required=True))

    request_ref = method.get("request", {}).get("$ref")
    if request_ref:
        body_doc = (
            f"The {request_ref} request body as a dict."
            f" Pass {{}} for an empty body where the API allows it."
        )
        body_schema = schemas.get(request_ref, {})
        fields = ", ".join(schema_fields_summary(body_schema))
        if fields:
            body_doc += f" Top-level fields: {{{fields}}}."
        params.append(make_param("body", "JsonDict", body_doc, "body", required=True))

    for pname in optional_names:
        prop = parameters[pname]
        annotation, extra_imports = prop_annotation(prop)
        doc = first_sentence(prop.get("description", "")) + enum_doc(prop)
        params.append(make_param(snake(pname), annotation, doc, pname))
        spec.imports |= extra_imports

    if add_fields_param:
        params.append(
            make_param(
                "fields",
                "Optional[str]",
                "Selector specifying which fields to include in the response."
                " The Drive API requires an explicit selector for full"
                ' comment/reply payloads; the default "*" returns all fields.',
                "fields",
                default_src='"*"',
            )
        )

    spec.params = params
    if request_ref:
        spec.imports.add("JsonDict")

    marker = "[DEVELOPER PREVIEW]" if preview else "[GA]"
    method_desc = normalize_text(method.get("description", ""))
    builder = DocstringBuilder(f"{marker} {api_title} API method {spec.source}.")
    builder.para(method_desc)
    builder.para(
        f"Auto-generated 1:1 wrapper for {http} {method.get('path', '')}"
        f" ({api_title} API)."
    )
    if preview:
        builder.para(
            "Google Workspace Developer Preview: requires preview program"
            " enrollment; without it the API returns an error."
        )
    doc_params_section(builder, params)
    builder.section("Returns:")
    response_ref = method.get("response", {}).get("$ref")
    if response_ref:
        ret = f"str: JSON-serialized {response_ref}."
        response_schema = schemas.get(response_ref, {})
        fields = "; ".join(schema_fields_summary(response_schema))
        if fields:
            ret += f" Fields: {fields}."
        builder.item(ret)
    else:
        builder.item(
            "str: A fixed success message (this API method returns an empty"
            " response body)."
        )
    spec.doc_lines = builder.render()

    required_entries = [
        f'        "{param["wire_name"]}": {param["py_name"]},'
        for param in params
        if param["required"] and param["wire_name"] != "body"
    ]
    if required_entries:
        body = ["    request_kwargs: dict[str, Any] = {"]
        body.extend(required_entries)
        body.append("    }")
    else:
        body = ["    request_kwargs: dict[str, Any] = {}"]
    if request_ref:
        body.append('    request_kwargs["body"] = body')
    for param in params:
        if not param["required"]:
            body.append(f"    if {param['py_name']} is not None:")
            body.append(
                f'        request_kwargs["{param["wire_name"]}"] = {param["py_name"]}'
            )
    body.append(
        f"    api_call = service.{resource_attr}().{method_name}(**request_kwargs)"
    )
    body.append("    response = await asyncio.to_thread(api_call.execute)")
    body.append("    if not response:")
    body.append('        return "Success: the API returned an empty response."')
    body.append("    return json.dumps(response, indent=2, sort_keys=True)")
    spec.body_lines = body
    return spec


def build_member_tool(
    member: str,
    member_prop: dict,
    schemas: dict,
    preview: bool,
    write_mode_available: bool,
    config: dict,
) -> ToolSpec:
    tool_name = f"docs_api_{snake(member)}"
    spec = ToolSpec(tool_name)
    spec.kind = "batch_member"
    spec.source = member
    spec.preview = preview
    spec.service_type = "docs"
    spec.scope_group = "docs_write"
    spec.read_only = False
    spec.destructive = member.startswith("delete")
    spec.title = (
        f"Docs API Preview: {member} (batchUpdate)"
        if preview
        else f"Docs API: {member} (batchUpdate)"
    )

    request_ref = member_prop.get("$ref", pascal(member) + "Request")
    request_schema = schemas.get(request_ref, {})
    suggest_unsupported = set(config.get("suggest_mode_unsupported", []))
    partial_notes = config.get("suggest_mode_partial", {})
    spec.write_mode = write_mode_available and member not in suggest_unsupported

    params: list[dict] = [
        make_param(
            "document_id",
            "str",
            "The ID of the document to update.",
            "documentId",
            required=True,
        )
    ]
    for pname in sorted(request_schema.get("properties", {})):
        prop = request_schema["properties"][pname]
        annotation, extra_imports = prop_annotation(prop)
        doc = first_sentence(prop.get("description", "")) + enum_doc(prop)
        doc += ref_schema_doc(prop, schemas)
        params.append(make_param(snake(pname), annotation, doc, pname))
        spec.imports |= extra_imports
    if spec.write_mode:
        doc = (
            "Optional writeControl.writeMode for this batchUpdate call."
            ' Use "SUGGEST" to apply this update as a suggestion instead of a'
            " direct edit (Developer Preview; requires enrollment)."
            " Omit for a normal edit."
        )
        if member in partial_notes:
            doc += " " + normalize_text(partial_notes[member])
        params.append(
            make_param(
                "write_mode",
                'Optional[Literal["EDIT", "SUGGEST"]]',
                doc,
                "writeMode",
            )
        )
        spec.imports.add("Literal")
    spec.params = params

    marker = "[DEVELOPER PREVIEW]" if preview else "[GA]"
    builder = DocstringBuilder(f"{marker} Docs API batchUpdate request {member}.")
    builder.para(normalize_text(request_schema.get("description", "")))
    builder.para(
        f"Auto-generated wrapper that sends a single {request_ref} via"
        " POST v1/documents/{documentId}:batchUpdate."
    )
    if preview:
        builder.para(
            "Google Workspace Developer Preview: requires preview program"
            " enrollment; without it the API rejects this request type."
            " Thread/suggestion updates can partially fail even when the"
            " batch succeeds; check commentUpdateState in the response."
        )
    doc_params_section(builder, params)
    builder.section("Returns:")
    response_schema = schemas.get("BatchUpdateDocumentResponse", {})
    ret = "str: JSON-serialized BatchUpdateDocumentResponse."
    fields = "; ".join(schema_fields_summary(response_schema))
    if fields:
        ret += f" Fields: {fields}."
    builder.item(ret)
    reply_ref = pascal(member) + "Response"
    if reply_ref in schemas:
        reply_fields = "; ".join(
            schema_fields_summary(schemas[reply_ref], spell_out=True)
        )
        builder.item(
            f"The reply for this request (in replies[0]) is {reply_ref}:"
            f" {reply_fields}."
        )
        for _, nested in sorted(schemas[reply_ref].get("properties", {}).items()):
            nested_ref = nested.get("$ref")
            if nested_ref and nested_ref in schemas:
                nested_fields = "; ".join(
                    schema_fields_summary(schemas[nested_ref], spell_out=True)
                )
                builder.item(f"{nested_ref} fields: {nested_fields}.")
    spec.doc_lines = builder.render()

    body = ["    request_body: dict[str, Any] = {}"]
    for param in params:
        if param["py_name"] in ("document_id", "write_mode"):
            continue
        body.append(f"    if {param['py_name']} is not None:")
        body.append(
            f'        request_body["{param["wire_name"]}"] = {param["py_name"]}'
        )
    body.append(
        f'    body: dict[str, Any] = {{"requests": [{{"{member}": request_body}}]}}'
    )
    if spec.write_mode:
        body.append("    if write_mode is not None:")
        body.append('        body["writeControl"] = {"writeMode": write_mode}')
    body.append(
        "    api_call = service.documents().batchUpdate("
        "documentId=document_id, body=body)"
    )
    body.append("    response = await asyncio.to_thread(api_call.execute)")
    body.append("    if not response:")
    body.append('        return "Success: the API returned an empty response."')
    body.append("    return json.dumps(response, indent=2, sort_keys=True)")
    spec.body_lines = body
    return spec


# ---------------------------------------------------------------------------
# Module assembly


def render_module(module_doc: str, specs: list[ToolSpec]) -> str:
    special = set()
    for spec in specs:
        special |= spec.imports
    lines = [GENERATED_HEADER.rstrip()]
    lines.append(module_doc)
    lines.append("")
    lines.append("import asyncio")
    lines.append("import json")
    typing_imports = ["Any"]
    if "Literal" in special:
        typing_imports.append("Literal")
    typing_imports.append("Optional")
    lines.append(f"from typing import {', '.join(typing_imports)}")
    lines.append("")
    lines.append("from mcp.types import ToolAnnotations")
    lines.append("")
    lines.append("from auth.service_decorator import require_google_service")
    lines.append("from core.server import server")
    util_imports = ["handle_http_errors"]
    for name in ("DictList", "JsonDict", "ObjectList", "StringList"):
        if name in special:
            util_imports.append(name)
    lines.append(f"from core.utils import {', '.join(sorted(util_imports))}")
    for spec in specs:
        lines.append("")
        lines.append("")
        lines.extend(spec.render())
    return "\n".join(lines) + "\n"


MODULE_DOCS = {
    "docs_methods": "# Google Docs API v1: documents.* resource methods.",
    "docs_batch_update": (
        "# Google Docs API v1: one tool per GA batchUpdate Request-union member."
    ),
    "docs_preview": (
        "# Google Docs API v1 Developer Preview: batchUpdate Request-union members\n"
        "# sourced from codegen/overlay/docs_preview_overlay.json (absent from\n"
        "# public discovery until preview enrollment)."
    ),
    "drive_comments": (
        "# Google Drive API v3: comments.* and replies.* resource methods."
    ),
}

INIT_TEMPLATE = (
    GENERATED_HEADER.rstrip()
    + "\n"
    + "# Importing this package registers every generated docs_preview tool on\n"
    + "# the shared FastMCP server via decorator side effects.\n"
    + "\n"
    + "from gdocs_preview.generated import docs_batch_update  # noqa: F401\n"
    + "from gdocs_preview.generated import docs_methods  # noqa: F401\n"
    + "from gdocs_preview.generated import docs_preview  # noqa: F401\n"
    + "from gdocs_preview.generated import drive_comments  # noqa: F401\n"
)


def generate(
    docs_path: Path | None = None,
    drive_path: Path | None = None,
    overlay_path: Path | None = None,
    config_path: Path | None = None,
) -> dict[str, str]:
    """Build all output files. Returns {relative_filename: content}."""
    docs_base = load_json(docs_path or DISCOVERY_DIR / "docs-v1.json")
    drive = load_json(drive_path or DISCOVERY_DIR / "drive-v3.json")
    overlay = load_json(overlay_path or OVERLAY_PATH)
    config = load_json(config_path or CONFIG_PATH)

    docs, preview_members, _preview_schemas = merge_overlay(docs_base, overlay)
    docs_schemas = docs.get("schemas", {})
    drive_schemas = drive.get("schemas", {})
    write_mode_available = "writeMode" in docs_schemas.get("WriteControl", {}).get(
        "properties", {}
    )

    base_methods = set(
        docs_base.get("resources", {}).get("documents", {}).get("methods", {})
    )

    modules: dict[str, list[ToolSpec]] = {
        "docs_methods": [],
        "docs_batch_update": [],
        "docs_preview": [],
        "drive_comments": [],
    }

    docs_methods = docs.get("resources", {}).get("documents", {}).get("methods", {})
    for method_name in sorted(docs_methods):
        spec = build_method_tool(
            api_name="docs",
            resource_name="documents",
            resource_attr="documents",
            method_name=method_name,
            method=docs_methods[method_name],
            schemas=docs_schemas,
            preview=method_name not in base_methods,
            service_type="docs",
            read_group="docs_read",
            write_group="docs_write",
            add_fields_param=False,
        )
        spec.module = "docs_methods"
        modules["docs_methods"].append(spec)

    request_members = docs_schemas.get("Request", {}).get("properties", {})
    for member in sorted(request_members):
        preview = member in preview_members
        spec = build_member_tool(
            member,
            request_members[member],
            docs_schemas,
            preview,
            write_mode_available,
            config,
        )
        spec.module = "docs_preview" if preview else "docs_batch_update"
        modules[spec.module].append(spec)

    for res_name in ("comments", "replies"):
        methods = drive.get("resources", {}).get(res_name, {}).get("methods", {})
        for method_name in sorted(methods):
            spec = build_method_tool(
                api_name="drive",
                resource_name=res_name,
                resource_attr=res_name,
                method_name=method_name,
                method=methods[method_name],
                schemas=drive_schemas,
                preview=False,
                service_type="drive",
                read_group="drive_read",
                write_group="drive",
                add_fields_param=True,
            )
            spec.module = "drive_comments"
            modules["drive_comments"].append(spec)

    files: dict[str, str] = {"__init__.py": INIT_TEMPLATE}
    for module_name, specs in modules.items():
        files[f"{module_name}.py"] = render_module(MODULE_DOCS[module_name], specs)

    manifest = {
        "service": "docs_preview",
        "tools": sorted(
            (
                {
                    "name": spec.name,
                    "module": spec.module,
                    "kind": spec.kind,
                    "source": spec.source,
                    "preview": spec.preview,
                    "read_only": spec.read_only,
                    "write_mode": spec.write_mode,
                }
                for specs in modules.values()
                for spec in specs
            ),
            key=lambda item: item["name"],
        ),
    }
    files["manifest.json"] = json.dumps(manifest, indent=2, sort_keys=True) + "\n"
    return files


def write_files(files: dict[str, str], out_dir: Path) -> list[str]:
    out_dir.mkdir(parents=True, exist_ok=True)
    written = []
    for name in sorted(files):
        path = out_dir / name
        content = files[name]
        if path.exists() and path.read_text(encoding="utf-8") == content:
            continue
        path.write_text(content, encoding="utf-8", newline="\n")
        written.append(name)
    return written


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--out",
        type=Path,
        default=DEFAULT_OUT_DIR,
        help=f"Output directory (default: {DEFAULT_OUT_DIR})",
    )
    args = parser.parse_args()
    files = generate()
    written = write_files(files, args.out)
    total = len(files)
    if written:
        print(f"Wrote {len(written)}/{total} files to {args.out}: {written}")
    else:
        print(f"All {total} files in {args.out} already up to date.")


if __name__ == "__main__":
    main()
