"""AUTO-GENERATED by codegen/generate.py. DO NOT EDIT BY HAND.

Regenerate with: python codegen/generate.py
Sources: committed discovery documents under codegen/discovery/ plus the
Developer Preview overlay codegen/overlay/docs_preview_overlay.json.
"""
# Google Docs API v1: documents.* resource methods.

import asyncio
import json
from typing import Any, Optional

from mcp.types import ToolAnnotations

from auth.service_decorator import require_google_service
from core.server import server
from core.utils import JsonDict, handle_http_errors


@server.tool(
    title="Docs API: documents.batchUpdate",
    annotations=ToolAnnotations(
        readOnlyHint=False,
        destructiveHint=False,
        idempotentHint=False,
        openWorldHint=True,
    ),
)
@handle_http_errors("docs_api_documents_batch_update", service_type="docs")
@require_google_service("docs", "docs_write")
async def docs_api_documents_batch_update(
    service: Any,
    user_google_email: str,
    document_id: str,
    body: JsonDict,
) -> str:
    """[GA] Docs API method docs.documents.batchUpdate.

    Applies one or more updates to the document.

    Auto-generated 1:1 wrapper for POST v1/documents/{documentId}:batchUpdate (Docs
    API).

    Args:
        user_google_email (str): The user's Google email address. Required.
        document_id (str): The ID of the document to update.
        body (dict): The BatchUpdateDocumentRequest request body as a dict. Pass {} for
            an empty body where the API allows it. Top-level fields: {requests
            (array<Request>), writeControl (WriteControl)}.

    Returns:
        str: JSON-serialized BatchUpdateDocumentResponse. Fields: documentId (string);
            replies (array<Response>): The reply of the updates..
    """
    request_kwargs: dict[str, Any] = {
        "documentId": document_id,
    }
    request_kwargs["body"] = body
    api_call = service.documents().batchUpdate(**request_kwargs)
    response = await asyncio.to_thread(api_call.execute)
    if not response:
        return "Success: the API returned an empty response."
    return json.dumps(response, indent=2, sort_keys=True)


@server.tool(
    title="Docs API: documents.get",
    annotations=ToolAnnotations(
        readOnlyHint=True,
        destructiveHint=False,
        idempotentHint=True,
        openWorldHint=True,
    ),
)
@handle_http_errors("docs_api_documents_get", is_read_only=True, service_type="docs")
@require_google_service("docs", "docs_read")
async def docs_api_documents_get(
    service: Any,
    user_google_email: str,
    document_id: str,
    suggestions_view_mode: Optional[str] = None,
) -> str:
    """[GA] Docs API method docs.documents.get.

    Gets the latest version of the specified document.

    Auto-generated 1:1 wrapper for GET v1/documents/{documentId} (Docs API).

    Args:
        user_google_email (str): The user's Google email address. Required.
        document_id (str): The ID of the document to retrieve.
        suggestions_view_mode (str): The suggestions view mode to apply to the document.
            Values: DEFAULT_FOR_CURRENT_ACCESS | SUGGESTIONS_INLINE.

    Returns:
        str: JSON-serialized Document. Fields: documentId (string); title (string).
    """
    request_kwargs: dict[str, Any] = {
        "documentId": document_id,
    }
    if suggestions_view_mode is not None:
        request_kwargs["suggestionsViewMode"] = suggestions_view_mode
    api_call = service.documents().get(**request_kwargs)
    response = await asyncio.to_thread(api_call.execute)
    if not response:
        return "Success: the API returned an empty response."
    return json.dumps(response, indent=2, sort_keys=True)
