"""AUTO-GENERATED by codegen/generate.py. DO NOT EDIT BY HAND.

Regenerate with: python codegen/generate.py
Sources: committed discovery documents under codegen/discovery/ plus the
Developer Preview overlay codegen/overlay/docs_preview_overlay.json.
"""
# Google Docs API v1 Developer Preview: batchUpdate Request-union members
# sourced from codegen/overlay/docs_preview_overlay.json (absent from
# public discovery until preview enrollment).

import asyncio
import json
from typing import Any, Optional

from mcp.types import ToolAnnotations

from auth.service_decorator import require_google_service
from core.server import server
from core.utils import handle_http_errors


@server.tool(
    title="Docs API Preview: acceptSuggestion (batchUpdate)",
    annotations=ToolAnnotations(
        readOnlyHint=False,
        destructiveHint=False,
        idempotentHint=False,
        openWorldHint=True,
    ),
)
@handle_http_errors("docs_api_accept_suggestion", service_type="docs")
@require_google_service("docs", "docs_write")
async def docs_api_accept_suggestion(
    service: Any,
    user_google_email: str,
    document_id: str,
    suggestion_id: Optional[str] = None,
) -> str:
    """[DEVELOPER PREVIEW] Docs API batchUpdate request acceptSuggestion.

    Accepts a suggestion. Returns a 403 forbidden error if the requesting user does not
    have edit access to the document.

    Auto-generated wrapper that sends a single AcceptSuggestionRequest via POST
    v1/documents/{documentId}:batchUpdate.

    Google Workspace Developer Preview: requires preview program enrollment; without it
    the API rejects this request type. Thread/suggestion updates can partially fail even
    when the batch succeeds; check commentUpdateState in the response.

    Args:
        user_google_email (str): The user's Google email address. Required.
        document_id (str): The ID of the document to update.
        suggestion_id (str): The ID of the suggestion.

    Returns:
        str: JSON-serialized BatchUpdateDocumentResponse. Fields: documentId (string);
            replies (array<Response>): The reply of the updates..
    """
    request_body: dict[str, Any] = {}
    if suggestion_id is not None:
        request_body["suggestionId"] = suggestion_id
    body: dict[str, Any] = {"requests": [{"acceptSuggestion": request_body}]}
    api_call = service.documents().batchUpdate(documentId=document_id, body=body)
    response = await asyncio.to_thread(api_call.execute)
    if not response:
        return "Success: the API returned an empty response."
    return json.dumps(response, indent=2, sort_keys=True)
