"""AUTO-GENERATED by codegen/generate.py. DO NOT EDIT BY HAND.

Regenerate with: python codegen/generate.py
Sources: committed discovery documents under codegen/discovery/ plus the
Developer Preview overlay codegen/overlay/docs_preview_overlay.json.
"""
# Google Docs API v1: one tool per GA batchUpdate Request-union member.

import asyncio
import json
from typing import Any, Literal, Optional

from mcp.types import ToolAnnotations

from auth.service_decorator import require_google_service
from core.server import server
from core.utils import JsonDict, handle_http_errors


@server.tool(
    title="Docs API: insertText (batchUpdate)",
    annotations=ToolAnnotations(
        readOnlyHint=False,
        destructiveHint=False,
        idempotentHint=False,
        openWorldHint=True,
    ),
)
@handle_http_errors("docs_api_insert_text", service_type="docs")
@require_google_service("docs", "docs_write")
async def docs_api_insert_text(
    service: Any,
    user_google_email: str,
    document_id: str,
    location: Optional[JsonDict] = None,
    text: Optional[str] = None,
    write_mode: Optional[Literal["EDIT", "SUGGEST"]] = None,
) -> str:
    """[GA] Docs API batchUpdate request insertText.

    Inserts text at the specified location.

    Auto-generated wrapper that sends a single InsertTextRequest via POST
    v1/documents/{documentId}:batchUpdate.

    Args:
        user_google_email (str): The user's Google email address. Required.
        document_id (str): The ID of the document to update.
        location (dict): Inserts the text at a specific index in the document. Object
            schema Location: {index (integer), segmentId (string)}.
        text (str): The text to be inserted.
        write_mode (str): Optional writeControl.writeMode for this batchUpdate call. Use
            "SUGGEST" to apply this update as a suggestion instead of a direct edit
            (Developer Preview; requires enrollment). Omit for a normal edit.

    Returns:
        str: JSON-serialized BatchUpdateDocumentResponse. Fields: documentId (string);
            replies (array<Response>): The reply of the updates..
    """
    request_body: dict[str, Any] = {}
    if location is not None:
        request_body["location"] = location
    if text is not None:
        request_body["text"] = text
    body: dict[str, Any] = {"requests": [{"insertText": request_body}]}
    if write_mode is not None:
        body["writeControl"] = {"writeMode": write_mode}
    api_call = service.documents().batchUpdate(documentId=document_id, body=body)
    response = await asyncio.to_thread(api_call.execute)
    if not response:
        return "Success: the API returned an empty response."
    return json.dumps(response, indent=2, sort_keys=True)
