"""AUTO-GENERATED by codegen/generate.py. DO NOT EDIT BY HAND.

Regenerate with: python codegen/generate.py
Sources: committed discovery documents under codegen/discovery/ plus the
Developer Preview overlay codegen/overlay/docs_preview_overlay.json.
"""
# Google Drive API v3: comments.* and replies.* resource methods.

import asyncio
import json
from typing import Any, Optional

from mcp.types import ToolAnnotations

from auth.service_decorator import require_google_service
from core.server import server
from core.utils import handle_http_errors


@server.tool(
    title="Drive API: comments.delete",
    annotations=ToolAnnotations(
        readOnlyHint=False,
        destructiveHint=True,
        idempotentHint=False,
        openWorldHint=True,
    ),
)
@handle_http_errors("drive_api_comments_delete", service_type="drive")
@require_google_service("drive", "drive")
async def drive_api_comments_delete(
    service: Any,
    user_google_email: str,
    file_id: str,
    comment_id: str,
    fields: Optional[str] = "*",
) -> str:
    """[GA] Drive API method drive.comments.delete.

    Deletes a comment.

    Auto-generated 1:1 wrapper for DELETE files/{fileId}/comments/{commentId} (Drive
    API).

    Args:
        user_google_email (str): The user's Google email address. Required.
        file_id (str): The ID of the file.
        comment_id (str): The ID of the comment.
        fields (str): Selector specifying which fields to include in the response. The
            Drive API requires an explicit selector for full comment/reply payloads; the
            default "*" returns all fields.

    Returns:
        str: A fixed success message (this API method returns an empty response body).
    """
    request_kwargs: dict[str, Any] = {
        "fileId": file_id,
        "commentId": comment_id,
    }
    if fields is not None:
        request_kwargs["fields"] = fields
    api_call = service.comments().delete(**request_kwargs)
    response = await asyncio.to_thread(api_call.execute)
    if not response:
        return "Success: the API returned an empty response."
    return json.dumps(response, indent=2, sort_keys=True)


@server.tool(
    title="Drive API: comments.list",
    annotations=ToolAnnotations(
        readOnlyHint=True,
        destructiveHint=False,
        idempotentHint=True,
        openWorldHint=True,
    ),
)
@handle_http_errors("drive_api_comments_list", is_read_only=True, service_type="drive")
@require_google_service("drive", "drive_read")
async def drive_api_comments_list(
    service: Any,
    user_google_email: str,
    file_id: str,
    include_deleted: Optional[bool] = None,
    page_size: Optional[int] = None,
    fields: Optional[str] = "*",
) -> str:
    """[GA] Drive API method drive.comments.list.

    Lists a file's comments.

    Auto-generated 1:1 wrapper for GET files/{fileId}/comments (Drive API).

    Args:
        user_google_email (str): The user's Google email address. Required.
        file_id (str): The ID of the file.
        include_deleted (bool): Whether to include deleted comments.
        page_size (int): The maximum number of comments to return per page.
        fields (str): Selector specifying which fields to include in the response. The
            Drive API requires an explicit selector for full comment/reply payloads; the
            default "*" returns all fields.

    Returns:
        str: JSON-serialized CommentList. Fields: comments (array<Comment>);
            nextPageToken (string).
    """
    request_kwargs: dict[str, Any] = {
        "fileId": file_id,
    }
    if include_deleted is not None:
        request_kwargs["includeDeleted"] = include_deleted
    if page_size is not None:
        request_kwargs["pageSize"] = page_size
    if fields is not None:
        request_kwargs["fields"] = fields
    api_call = service.comments().list(**request_kwargs)
    response = await asyncio.to_thread(api_call.execute)
    if not response:
        return "Success: the API returned an empty response."
    return json.dumps(response, indent=2, sort_keys=True)
