"""Build the scenario corpus.

    uv run python -m llmux.scenarios.generate            # rewrite generated/
    uv run python -m llmux.scenarios.generate --only easy-kind-split

Each scenario is built twice and the two builds must agree:

1. **the model path** -- the oracle steps applied to a seeded backend through
   ``MockDoc``/``FakeBackend`` directly. This is where ``expected.json`` is
   read off, so ground truth is a statement about SPEC §7, not about the
   adapter or the tools.
2. **the API path** -- the same steps replayed as real MCP tool calls against
   a second seeded backend.

If they differ, generation fails. That is the whole guard against the obvious
failure mode of a self-generated corpus: an oracle that is wrong in the same
way as the expectation it produces. Two independent implementations of the
same intent (grapheme model vs UTF-16 API surface) have to be wrong in the
same way to slip through, and the UTF-16 conversion alone makes that
unlikely -- an off-by-one anchor shows up as a mismatched comment quote.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any, Optional

from mockdocs.model import MockDoc

from llmux.scenarios.catalog import CATALOG, Scenario
from llmux.scenarios.grading import grade_against
from llmux.scenarios.oracle import run_solution
from llmux.scenarios.primitives import seeded_backend
from llmux.scenarios.steps import OracleContext

GENERATED = Path(__file__).resolve().parent / "generated"

GRADE_TEMPLATE = '''"""Grade `{scenario_id}` -- generated by llmux.scenarios.generate.

Do not edit: rebuild with ``python -m llmux.scenarios.generate``. The whole
judgement lives in ``expected.json``; this module only points the shared
end-state grader at it.
"""

from __future__ import annotations

import sys
from pathlib import Path
from typing import Any

_HERE = Path(__file__).resolve()
_REPO_ROOT = _HERE.parents[4]
if str(_REPO_ROOT) not in sys.path:  # importable from anywhere
    sys.path.insert(0, str(_REPO_ROOT))

from llmux.scenarios.grading import grade_scenario  # noqa: E402


def grade(backend: Any) -> dict[str, Any]:
    """Grade the post-run backend against this scenario's expected end state."""
    return grade_scenario(backend, _HERE.parent)
'''


class GenerationError(RuntimeError):
    """A scenario failed to build or its two builds disagreed."""


# ---------------------------------------------------------------------------
# state snapshots (for the model-vs-API cross-check)
# ---------------------------------------------------------------------------


def snapshot(backend: Any, document_id: str) -> dict[str, Any]:
    """Everything a grader can see, in a comparable shape.

    Post ids are deliberately excluded: the two paths allocate comment
    counters in a different order, and an id is not part of the end state
    anyone grades.
    """
    doc: MockDoc = backend.get_document(document_id)
    return {
        "display": doc.display_text(),
        "original": doc.original_text(),
        "final": doc.final_text(),
        "registry": sorted(doc.registry),
        "marks": [[c.cp, sorted(c.ins), sorted(c.dels)] for c in doc.chars if c.marks],
        "threads": {
            sid: [(p.author, p.content) for p in doc.registry[sid].thread]
            for sid in sorted(doc.registry)
        },
        "comments": [
            [
                t.get("plainTextQuote", ""),
                (t.get("headPost") or {}).get("content", ""),
                [p.get("content", "") for p in (t.get("replies") or [])],
            ]
            for t in backend.comments.get(document_id) or []
        ],
    }


def _diff(model: dict[str, Any], api: dict[str, Any]) -> list[str]:
    return [
        f"{key}: model={model[key]!r} api={api[key]!r}"
        for key in sorted(model)
        if model[key] != api[key]
    ]


# ---------------------------------------------------------------------------
# build
# ---------------------------------------------------------------------------


def build(scenario: Scenario) -> dict[str, Any]:
    """Emit the solution, compute ground truth, cross-check, return the files."""
    model_backend, doc = seeded_backend(scenario.seed)
    seeded_ids = sorted(doc.registry)
    if not seeded_ids:
        raise GenerationError(f"{scenario.id}: seed produced no suggestions")

    ctx = OracleContext(model_backend, scenario.document_id)
    calls: list[dict[str, Any]] = []
    expectations: list[dict[str, Any]] = []
    resolved: dict[str, str] = {}
    for i, step in enumerate(scenario.steps):
        try:
            call, step_expectations = step.emit(ctx)
        except Exception as exc:
            raise GenerationError(
                f"{scenario.id}: step {i} ({type(step).__name__}) failed to emit: {exc}"
            ) from exc
        calls.append(call)
        expectations.extend(step_expectations)
        if step.decision is not None:
            sid, action = step.decision
            resolved[sid] = action

    model_state = snapshot(model_backend, scenario.document_id)

    api_backend, _ = seeded_backend(scenario.seed)
    run_solution(api_backend, scenario.document_id, calls)
    api_state = snapshot(api_backend, scenario.document_id)

    differences = _diff(model_state, api_state)
    if differences:
        raise GenerationError(
            f"{scenario.id}: the model path and the tool path disagree -- "
            + "; ".join(differences)
        )

    surviving = model_state["registry"]
    # A resolved suggestion takes its thread with it (§7 + §10): expectations
    # about replies are only gradeable on suggestions that are still open.
    thread_expectations = [
        exp
        for exp in expectations
        if exp.get("kind") != "suggestion_reply"
        or exp.get("suggestion_id") in surviving
    ]

    invariant_checks: list[dict[str, Any]] = [
        {"check": "model_invariants"},
        {
            "check": "projection_text",
            "projection": "original",
            "equals": model_state["original"],
        },
        {
            "check": "projection_text",
            "projection": "final",
            "equals": model_state["final"],
        },
    ]
    invariant_checks.extend(scenario.extra_checks)

    expected = {
        "document_id": scenario.document_id,
        "final_text": model_state["display"],
        "surviving_suggestion_ids": surviving,
        "resolved": resolved,
        "thread_expectations": thread_expectations,
        "invariant_checks": invariant_checks,
    }

    verdict = grade_against(api_backend, expected)
    if not verdict["pass"] or verdict["score"] != 1.0:
        raise GenerationError(
            f"{scenario.id}: the oracle solution does not grade clean: {verdict}"
        )

    meta = {
        "id": scenario.id,
        "difficulty": scenario.difficulty,
        "steps": len(calls),
        "tags": list(scenario.tags),
        "authors": list(scenario.authors),
        "n_suggestions": scenario.n_suggestions,
        # Beyond the frozen contract, for the runner's convenience:
        "tier": scenario.tier,
        "document_id": scenario.document_id,
        "me": scenario.seed.get("me", "mockuser"),
        "env": {"MOCKDOCS_SEED": "seed.json"},
    }

    return {
        "seed.json": scenario.seed,
        "expected.json": expected,
        "meta.json": meta,
        "solution.json": calls,
        "brief.md": scenario.brief,
        "grade.py": GRADE_TEMPLATE.format(scenario_id=scenario.id),
    }


def check_brief(scenario: Scenario, seeded_ids: list[str]) -> list[str]:
    """The brief must not hand the agent anything it should discover.

    Naming a suggestion id turns a review task into an id-plumbing task and
    quietly removes the read step -- which is the part of the tool surface
    most worth measuring.
    """
    problems = []
    for sid in seeded_ids:
        if sid in scenario.brief:
            problems.append(f"brief names suggestion id {sid}")
    if "sug." in scenario.brief:
        problems.append("brief contains a raw 'sug.' suggestion id")
    if "comment." in scenario.brief:
        problems.append("brief contains a raw 'comment.' thread id")
    if scenario.document_id not in scenario.brief:
        problems.append("brief does not state the document id")
    return problems


def write(scenario: Scenario, files: dict[str, Any], root: Path) -> Path:
    target = root / scenario.id
    target.mkdir(parents=True, exist_ok=True)
    for name, payload in files.items():
        path = target / name
        if isinstance(payload, str):
            path.write_text(payload, encoding="utf-8")
        else:
            path.write_text(
                json.dumps(payload, indent=2, ensure_ascii=False) + "\n",
                encoding="utf-8",
            )
    return target


def generate(only: Optional[list[str]] = None, root: Path = GENERATED) -> list[str]:
    written: list[str] = []
    for factory in CATALOG:
        scenario = factory()
        if only and scenario.id not in only:
            continue
        _, doc = seeded_backend(scenario.seed)
        problems = check_brief(scenario, sorted(doc.registry))
        if problems:
            raise GenerationError(f"{scenario.id}: " + "; ".join(problems))
        files = build(scenario)
        write(scenario, files, root)
        written.append(scenario.id)
    return written


def main(argv: Optional[list[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--only", nargs="*", help="scenario ids to rebuild")
    parser.add_argument("--root", default=str(GENERATED), help="output directory")
    args = parser.parse_args(argv)

    root = Path(args.root)
    try:
        written = generate(only=args.only, root=root)
    except GenerationError as exc:
        print(f"generation failed: {exc}", file=sys.stderr)
        return 1
    for scenario_id in written:
        print(f"wrote {root / scenario_id}")
    print(f"{len(written)} scenario(s)")
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
