"""docs_preview service: hand-written Google Docs review surface.

Curated review tools (suggestion diffing, capabilities probe,
reviewer-view read) live in :mod:`gdocs_preview.curated_tools`; the
native suggestion/comment write tools (SUGGEST-mode edits, accept/reject,
thread replies, anchored comments) live in
:mod:`gdocs_preview.write_tools` (see
docs/plans/2026-07-14-native-integration.md). The former autogenerated
API-parity layer was removed in the 2026-07-29 redirect - its API
knowledge is preserved in docs/preview-api-reference.md.

Importing this package registers the tools on the shared FastMCP server
via decorator side effects.
"""

from gdocs_preview import curated_tools  # noqa: F401
from gdocs_preview import write_tools  # noqa: F401
