"""docs_preview service: hand-written Google Docs review surface.

Curated review tools (suggestion diffing, capabilities probe,
reviewer-view read) live in :mod:`gdocs_preview.curated_tools`; native
suggestion/comment tools are added alongside them (see
docs/plans/2026-07-14-native-integration.md). The former autogenerated
API-parity layer was removed in the 2026-07-29 redirect - its API
knowledge is preserved in docs/preview-api-reference.md.

Importing this package registers the tools on the shared FastMCP server
via decorator side effects.
"""

from gdocs_preview import curated_tools  # noqa: F401
